using Godot;
using System;
using System.Threading.Tasks;

// Headless verifier for the sandbox test levels generated by GenerateSandboxLevels.cs.
//
// Asserts that SandboxHub / SandboxGrasslands / SandboxDepths exist, have correct
// root types, non-empty tilemaps, and that every LevelTransition resolves to a
// direct-root transition in its target scene (bidirectional door wiring).
//
// Run with: godot --headless --path . --script res://tests/VerifySandboxLevels.cs

public partial class VerifySandboxLevels : SceneTree
{
    private int _failures;

    public override async void _Initialize()
    {
        GD.Print("[sandbox] Starting verification...");

        await VerifyLevel("res://levels/sandbox/maps/SandboxHub.tscn", "Sandbox Hub", 3);
        await VerifyLevel("res://levels/sandbox/maps/SandboxGrasslands.tscn", "Sandbox Grasslands", 1);
        await VerifyLevel("res://levels/sandbox/maps/SandboxDepths.tscn", "Sandbox Depths", 1);
        await VerifyWarpRegistration();

        if (_failures == 0)
            GD.Print("[sandbox] ALL CHECKS PASSED");
        else
            GD.PrintErr($"[sandbox] {_failures} FAILURE(S)");

        System.Environment.Exit(_failures == 0 ? 0 : 1);
    }

    private async Task VerifyLevel(string scenePath, string expectedName, int expectedExits)
    {
        if (!FileAccess.FileExists(scenePath))
        {
            Fail($"[{expectedName}] Scene file not found at {scenePath}");
            return;
        }

        var scene = ResourceLoader.Load<PackedScene>(scenePath);
        if (scene == null)
        {
            Fail($"[{expectedName}] Could not load PackedScene from {scenePath}");
            return;
        }

        var root = scene.Instantiate() as Node2D;
        if (root == null)
        {
            Fail($"[{expectedName}] Instantiated root is not Node2D");
            return;
        }

        if (root is not BaseLevel)
            Fail($"[{expectedName}] Root '{root.Name}' is not BaseLevel");
        if (root is BaseLevel bl && bl.LevelName != expectedName)
            Fail($"[{expectedName}] LevelName is '{bl.LevelName}', expected '{expectedName}'");

        var tilemap = root.GetNodeOrNull<LevelTileMapLayer>("CoreTilemapLayer");
        if (tilemap == null)
            Fail($"[{expectedName}] Missing direct-root CoreTilemapLayer of type LevelTileMapLayer");
        else
        {
            var usedRect = tilemap.GetUsedRect();
            if (usedRect.Size == Vector2I.Zero)
                Fail($"[{expectedName}] CoreTilemapLayer has empty used rect");
            else
                GD.Print($"[{expectedName}] CoreTilemapLayer used rect: {usedRect}");
        }

        int exits = 0;
        foreach (Node child in root.GetChildren())
        {
            if (child is not LevelTransition transition)
                continue;
            exits++;
            if (string.IsNullOrEmpty(transition.Level) || !FileAccess.FileExists(transition.Level))
            {
                Fail($"[{expectedName}] {transition.Name} has non-loadable Level '{transition.Level}'");
                continue;
            }
            if (string.IsNullOrEmpty(transition.TargetTransitionName))
            {
                Fail($"[{expectedName}] {transition.Name} has empty TargetTransitionName");
                continue;
            }

            var targetPacked = ResourceLoader.Load<PackedScene>(transition.Level);
            var targetRoot = targetPacked?.Instantiate() as Node2D;
            if (targetRoot == null)
            {
                Fail($"[{expectedName}] {transition.Name} target '{transition.Level}' cannot instantiate");
                continue;
            }

            var target = targetRoot.GetNodeOrNull<LevelTransition>(transition.TargetTransitionName);
            if (target == null)
                Fail($"[{expectedName}] {transition.Name} → {transition.Level}/{transition.TargetTransitionName} NOT FOUND");
            else
                GD.Print($"[{expectedName}] {transition.Name} → {transition.Level}/{transition.TargetTransitionName} OK");

            targetRoot.Free();
            await ToSignal(this, SceneTree.SignalName.ProcessFrame);
        }

        if (exits != expectedExits)
            Fail($"[{expectedName}] Expected {expectedExits} exit transitions, found {exits}");

        root.Free();
        await ToSignal(this, SceneTree.SignalName.ProcessFrame);
    }

    private async Task VerifyWarpRegistration()
    {
        foreach (string id in new[] { "sandbox_hub", "sandbox_grasslands", "sandbox_depths" })
        {
            if (!WarpDatabase.All.TryGetValue(id, out var dest))
            {
                Fail($"[Warp] Missing WarpDatabase entry '{id}'");
                continue;
            }
            if (!FileAccess.FileExists(dest.LevelPath))
                Fail($"[Warp] '{id}' LevelPath missing: {dest.LevelPath}");

            var packed = ResourceLoader.Load<PackedScene>(dest.LevelPath);
            var root = packed?.Instantiate() as Node2D;
            if (root == null)
            {
                Fail($"[Warp] '{id}' destination cannot instantiate");
                continue;
            }
            if (root.GetNodeOrNull<LevelTransition>(dest.TargetTransitionName) == null)
                Fail($"[Warp] '{id}' TargetTransitionName '{dest.TargetTransitionName}' not found in {dest.LevelPath}");
            else
                GD.Print($"[Warp] '{id}' → {dest.LevelPath}/{dest.TargetTransitionName} OK");
            root.Free();
            await ToSignal(this, SceneTree.SignalName.ProcessFrame);
        }
    }

    private void Fail(string msg)
    {
        _failures++;
        GD.PrintErr(msg);
    }
}